{
  description = "characterminator -- eliminate characters outside an allowed set (dev shell)";

  # hk is built by `nix-hk` and pushed to this cache. Without the substituter
  # every entry into the dev shell BUILDS hk from source, which is the cost
  # this wiring exists to avoid.
  nixConfig = {
    extra-substituters = [ "https://pr0d1r2.cachix.org" ];
    extra-trusted-public-keys = [
      "pr0d1r2.cachix.org-1:NfWjbhgAj41byXhCKiaE+av3Vnphm1fTezHXEGsiQIM="
    ];
  };

  # ONE nixpkgs. `nixpkgs-lock` is the fleet's sole nixpkgs authority
  # (nixos-26.05, rustc 1.95.0) and every other input follows it. An input
  # that resolved its own revision would put a second toolchain in the
  # closure and miss every substitution.
  #
  # The three tool inputs are pinned to TAGS, not branches: the rules this
  # repo is held to should change when a pin changes and at no other time.
  inputs = {
    nixpkgs-lock.url = "github:pr0d1r2/nixpkgs-lock";
    nixpkgs.follows = "nixpkgs-lock/nixpkgs";
    nix-hk.url = "github:pr0d1r2/nix-hk";
    nix-hk.inputs.nixpkgs-lock.follows = "nixpkgs-lock";
    # The FORMAT owner: SPEC.md's structural rules have one implementation
    # and this repo CALLS it. v0.7.0 was the first tag that understood the
    # federation sections; 0.6.x reformats them as if they were prose. 0.7.3
    # adds what a federated tree needs: a dangling cross-node citation is
    # named rather than passed over, and a task row this build cannot read is
    # counted instead of reading as absent.
    microlith.url = "github:pr0d1r2/microlith/v0.7.3";
    microlith.inputs.nixpkgs-lock.follows = "nixpkgs-lock";
    microlith.inputs.nix-hk.follows = "nix-hk";
    # Token counts and the git-tracked fileset. One token authority in the
    # fleet, so a saving reported here matches what itok reports elsewhere.
    itok.url = "github:pr0d1r2/itok/v0.3.1";
    itok.inputs.nixpkgs-lock.follows = "nixpkgs-lock";
    itok.inputs.hk.follows = "nix-hk";
    # The federation checker for this repo's own spec tree.
    sherd.url = "github:pr0d1r2/sherd/v0.5.0";
    sherd.inputs.nixpkgs-lock.follows = "nixpkgs-lock";
    sherd.inputs.nix-hk.follows = "nix-hk";
  };

  outputs =
    {
      nixpkgs,
      nix-hk,
      microlith,
      itok,
      sherd,
      ...
    }:
    let
      systems = [
        "aarch64-darwin"
        "x86_64-linux"
        "aarch64-linux"
      ];
      # The overlay is what makes `pkgs.hk` mean nix-hk's hk rather than
      # nixpkgs'. Applied as an overlay so there is exactly one `pkgs` here.
      forAll =
        f:
        nixpkgs.lib.genAttrs systems (
          s: f (nixpkgs.legacyPackages.${s}.extend nix-hk.overlays.default)
        );

      # A git hook written BY HAND rather than by `hk install`. An installed
      # hook assumes its own binary is on PATH; outside this shell it is not,
      # so it would make every git command fail rather than run ungated. This
      # one degrades LOUDLY: one line to stderr, exit 0.
      #
      # Copied into `.git/hooks` rather than symlinked: a symlink into the
      # store dangles after a GC, and a dangling hook makes git error out.
      gitHook =
        pkgs: name:
        pkgs.writeText "characterminator-${name}-hook" ''
          #!/bin/sh
          # Generated by the dev shell (flake.nix), rewritten on every entry.
          # Edit the shellHook there, not this copy.
          command -v hk >/dev/null 2>&1 || {
            echo "hk: not on PATH -- SKIPPING the ${name} gate. Enter the dev shell (\`direnv allow\` or \`nix develop\`) to run it." >&2
            exit 0
          }
          exec hk run ${name} "$@"
        '';

      # The llvm that READS coverage data, pinned to the major `rustc` was
      # built against (21, as `rustc -vV` reports). Named once here because
      # it is referenced three times below: as a package, and as the two
      # environment variables `cargo llvm-cov` reads.
      #
      # A BARE `pkgs.llvmPackages.llvm` WOULD BE WRONG. That is nixpkgs'
      # default llvm, which tracks its own schedule and is not promised to
      # be the one inside `pkgs.rustc`. When those differ the failure is a
      # `.profraw` version error in the middle of a coverage run, which
      # reads as a broken test rather than as a pin to update -- so the
      # gate compares the two majors and says which it is (V46).
      coverageLlvm = pkgs: pkgs.llvmPackages_21.llvm;

      # The reproducible build. Possible because the flake sits at the root
      # and `Cargo.lock` is tracked: flakes copy git-tracked files into the
      # store and the build sandbox has no network, so the lock is what lets
      # nix vendor crates offline.
      ctrmPkg =
        pkgs:
        pkgs.rustPlatform.buildRustPackage {
          pname = "characterminator";
          # Read from Cargo.toml so there is ONE version, never two that can
          # disagree.
          version =
            (builtins.fromTOML (builtins.readFile ./Cargo.toml)).package.version;
          # Only what the BUILD reads. With `src = ./.` every tracked file is
          # an input, so editing a SPEC.md would rebuild the crate.
          src = pkgs.lib.fileset.toSource {
            root = ./.;
            fileset = pkgs.lib.fileset.unions [
              ./src
              ./Cargo.toml
              ./Cargo.lock
            ];
          };
          cargoLock.lockFile = ./Cargo.lock;
          meta = {
            description = "find and eliminate characters outside an allowed set";
            homepage = "https://github.com/pr0d1r2/characterminator";
            license = pkgs.lib.licenses.mit;
            mainProgram = "ctrm";
          };
        };
    in
    {
      packages = forAll (pkgs: {
        default = ctrmPkg pkgs;
      });

      devShells = forAll (pkgs: {
        default = pkgs.mkShell {
          packages = [
            pkgs.rustc
            pkgs.cargo
            pkgs.clippy
            pkgs.rustfmt
            pkgs.git
            # The gate runner; the ops it runs live in `hk.pkl`. From the
            # nix-hk overlay rather than nixpkgs, whose hk trails the
            # releases `hk.pkl` is written against.
            pkgs.hk
            # The three fleet tools the gate calls, pinned so the dev shell
            # and CI run identical versions. The binary names differ from
            # their crate names: microlith installs `mth`.
            microlith.packages.${pkgs.stdenv.hostPlatform.system}.default
            itok.packages.${pkgs.stdenv.hostPlatform.system}.default
            sherd.packages.${pkgs.stdenv.hostPlatform.system}.default
            # `nixfmt --check` gates this very file: the flake decides what
            # every other step runs with, so drift here is drift everywhere.
            pkgs.nixfmt
            # Line coverage (V46). `cargo llvm-cov` drives the instrumented
            # build; the llvm tools that READ what it produces come from the
            # package below, because they are not in nixpkgs' rustc.
            pkgs.cargo-llvm-cov
            (coverageLlvm pkgs)
          ];
          # Pin locale so tool output is deterministic across machines.
          LANG = "C.UTF-8";
          # WHERE `cargo llvm-cov` LOOKS. Without these it searches for a
          # rustup `llvm-tools-preview` component that a nix toolchain does
          # not have, and fails with a message about installing rustup.
          #
          # The version has to MATCH the LLVM rustc was built against: a
          # `.profraw` carries a format version, and an older `llvm-profdata`
          # rejects a newer one. The gate asserts the two majors agree
          # (V46) rather than trusting this line to stay true through a
          # `nixpkgs-lock` bump.
          LLVM_COV = "${coverageLlvm pkgs}/bin/llvm-cov";
          LLVM_PROFDATA = "${coverageLlvm pkgs}/bin/llvm-profdata";
          # Entering installs the git hooks, unconditionally rewriting them,
          # so the hook a contributor has is always the one this file
          # describes.
          #
          # `git rev-parse --git-path hooks` rather than a literal
          # `.git/hooks`: in a worktree or a submodule `.git` is a FILE and
          # the real hooks directory is elsewhere.
          shellHook = ''
            # TWO guards before writing a hook, both earned by B1: this shell
            # was entered from a SIBLING repo to borrow a tool, and it
            # installed OUR hooks over that repo's tracked ones, downgrading
            # its gate from refuse to skip without a word.
            #
            # 1. Only our own repo. The marker is this crate's name in its own
            #    manifest, checked at the worktree root, because a dev shell
            #    may legitimately be entered from anywhere.
            # 2. Only an UNTRACKED hooks directory. `core.hooksPath` can point
            #    at a tracked directory -- sherd does exactly that, so its
            #    hooks are reviewable in a diff -- and writing there edits
            #    files git is watching.
            ctrm_root="$(git rev-parse --show-toplevel 2>/dev/null || true)"
            ctrm_hooks="$(git rev-parse --git-path hooks 2>/dev/null || true)"
            if [ -z "$ctrm_root" ] || ! grep -q '^name = "characterminator"$' "$ctrm_root/Cargo.toml" 2>/dev/null; then
              echo "characterminator(shell): not this repo -- hooks NOT installed (B1)" >&2
            elif git -C "$ctrm_root" ls-files --error-unmatch "$ctrm_hooks" >/dev/null 2>&1; then
              echo "characterminator(shell): $ctrm_hooks is TRACKED -- refusing to overwrite a reviewed hook (B1)" >&2
            elif [ -n "$ctrm_hooks" ] && [ -d "$ctrm_hooks" ]; then
              install -m 755 ${gitHook pkgs "pre-commit"} "$ctrm_hooks/pre-commit"
              install -m 755 ${gitHook pkgs "pre-push"} "$ctrm_hooks/pre-push"
            else
              echo "characterminator(shell): no git hooks directory -- nothing is gating" >&2
            fi
            unset ctrm_root ctrm_hooks
          '';
        };
      });
    };
}
